import type { ResponsiveImage } from '@/types/project'

/** Every variant generated by `npm run images`, keyed by path → built URL. */
const files = import.meta.glob<string>('../assets/images/*.{avif,webp}', {
  eager: true,
  import: 'default',
})

/**
 * Builds a `ResponsiveImage` from the variants of one generated image
 * (`<name>-<width>.avif|webp`). `size` is the largest variant, which also
 * serves as the fallback `src`.
 */
export function responsiveImage(
  name: string,
  widths: number[],
  size: { width: number; height: number },
  alt: string,
): ResponsiveImage {
  const url = (width: number, format: 'avif' | 'webp') => {
    const file = files[`../assets/images/${name}-${width}.${format}`]
    if (!file) throw new Error(`Missing image ${name}-${width}.${format}: run npm run images`)
    return file
  }
  const srcSet = (format: 'avif' | 'webp') =>
    widths.map((width) => `${url(width, format)} ${width}w`).join(', ')

  return {
    avif: srcSet('avif'),
    webp: srcSet('webp'),
    src: url(Math.max(...widths), 'webp'),
    ...size,
    alt,
  }
}
