/**
 * SEO content — single source for the client (useSeo) and the build
 * (scripts/vite-plugin-seo.ts: per-route HTML, sitemap, robots). Plain data
 * only: no `@/` alias, no asset import, so Node can load it at build time.
 * See docs/seo.md.
 */

export interface PersonSeo {
  name: string
  jobTitle: string
  description: string
  /** Skills stated on the home page. */
  knowsAbout: string[]
}

export interface PageSeo {
  /** Full `<title>` (also og:title / twitter:title). */
  metaTitle: string
  metaDescription: string
  /** Social image in /public (1200 × 630), generated by `npm run images`. */
  ogImage: string
  ogImageAlt: string
}

export interface ProjectSeo extends PageSeo {
  /** Matches `Project.slug`; the route is /projects/<slug>. */
  slug: string
  /** Project name (structured data, breadcrumb). */
  title: string
  /** Canonical path, when it differs from /projects/<slug>. */
  canonical?: string
  year: string
  client: string
}

export const person: PersonSeo = {
  name: 'Fatou Fofana',
  jobTitle: 'UI/UX Designer',
  description: 'UI/UX Designer spécialisée en conception d’interfaces web et mobile.',
  knowsAbout: [
    'Conception d’interfaces web et mobile',
    'Recherche utilisateur',
    'Prototypage',
    'Design Systems',
    'UI Design',
    'Tests utilisateurs',
  ],
}

export const siteSeo = {
  siteName: 'Fatou Fofana — UI/UX Designer',
  locale: 'fr_FR',
  language: 'fr-FR',
}

export const homeSeo: PageSeo = {
  metaTitle: 'Fatou Fofana — UI/UX Designer | Design web & mobile',
  metaDescription:
    'Fatou Fofana, UI/UX Designer spécialisée dans la conception d’interfaces web et mobile, la recherche utilisateur, le prototypage et les Design Systems.',
  ogImage: '/og/home.jpg',
  ogImageAlt: 'Illustration de Fatou Fofana, UI/UX Designer, devant son ordinateur portable.',
}

/** Public case studies, in home page order. Every page in data/case-studies needs an entry. */
export const projectsSeo: ProjectSeo[] = [
  {
    slug: 'exmed',
    title: 'EXMED DA OPO PHONO',
    metaTitle: 'EXMED DA OPO PHONO — UI/UX Design | Fatou Fofana',
    metaDescription:
      'Découvrez le projet EXMED DA OPO PHONO réalisé pour la SACEM : refonte et création de logo, wireframes, prototype et conception UI/UX.',
    ogImage: '/og/exmed.jpg',
    ogImageAlt:
      'Écran d’accueil de DA OPO PHONO by Exmed : cartes des applications sur fond violet.',
    year: '2024',
    client: 'SACEM',
  },
  {
    slug: 'ste-soeurs',
    title: 'Ste SŒURS',
    metaTitle: 'Ste SŒURS — Refonte UI | Fatou Fofana, UI/UX Designer',
    metaDescription:
      'Découvrez la refonte UI du portail Ste SŒURS réalisée par Fatou Fofana, UI/UX Designer pour la SACEM : interfaces, harmonisation UI et conception d’un Design System réutilisable.',
    ogImage: '/og/ste-soeurs.jpg',
    ogImageAlt: 'Landing page du portail SACEM Ste SŒURS : « SACEM Portal » et bouton « Log in ».',
    year: '2023',
    client: 'SACEM',
  },
]
